### ISSUE TITLE
QA: Multiple ports Cloud Foundry app

### ISSUE THREAD

**Issue by bobbui** [MonsantoCo/prom-cf-sd#1]
Hi,
Firstly, Thank for your repository. It's really useful.
I have a question but not sure where to ask it so open an issue here.
I've been exploring Prometheus to monitoring the application running in Cloud Foundry.
The application will serve normal request via one port and Prometheus will open another one to serve the metrics requests.
I wonder how we can expose multiple ports in CF?

Thanks and Regards,
Thang Bob

**Comment by mjseid** [comment]
Hey, 
    I know the question of multiple app ports has been asked in the CF community sites, and I believe it's on the roadmap.  But at this time I do not think its currently supported.

For prometheus usually the client library just piggy-backs on whatever middleware you're running for your app and exposes another route (/metrics) using the same port (set from the PORT environment variable on CloudFoundry) your middleware is already using.

**Comment by bobbui** [comment]
Thanks for the answer. I'm also thinking the same thing but implement this will require implementation for every framework we're using.

**Comment by bobbui** [comment]
Just want to have another follow-up question:

I've managed to get it working with metrics are exposed at the same main application port. But Prometheus can not reach the application's instance IP and port got from service discovery. Prometheus and applications were deployed in same CF spaces.
Do we need to do anything on CF network configuration?

Highly appreciate your answer.

Regards,
Bob Thang

**Comment by mjseid** [comment]
Cool, glad you got it working.

You're correct that there needs to be network availability between prometheus and your CF cells.  In our setup we have prometheus deployed on a separate docker host in the same subnets as cloudfoundry so there is open network communication between the two.  We also don't use any app security groups within CF.

I'd double check your routing tables and firewall configuration between prometheus and the CF Cells.  Maybe start by just ssh-ing to the host/container running prometheus and trying to curl the app IP:PORT  or doing a traceroute and seeing how far you get.

**Comment by bobbui** [comment]
Hi Mark,
So you deployed Prometheus outside of your CF, and it can connect to application instances in CF in the same network? 
What I have currently is Prometheus inside CF. I tried to ssh into the Prometheus container and do all kind of wget/curl/ping to application instance port with no success.
There is a "allow_host_access" configuration option, look like toggle it on will enable network access between host inside CF. But it will require bosh re-deploy, which unfortunately I don't have access to in my company.
I also will check on the application security group as well.

Thanks again for your help.
